package:
  name: "asfjzdemo"
  version: "1.1.0"

source:
  git_rev: v.1.1.0
  git_url: https://github.com/cirrusasf/demo_publish_to_conda

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python

about:
  home: https://github.com/cirrusasf/demo_publish_to_conda
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Demo for publishing the simple python package to conda"

extra:
  recipe-maintainers:
    - cirrusasf
